#ifndef ENUMERATIONS_H
#define ENUMERATIONS_H


enum class RolePro
{
    MEDECIN_GENERALE,
    MEDECIN_SPECIALISTE,
    INFIRMIER,
    PHARMACIEN,
    SAGE_FEMME,
    DENTISTE,
    TECHNICIEN_LABORATOIRE,
    RADIOLOGUE
};
enum class Specialite
{
    MEDECINE_GENERALE,
    PEDIATRIE,
    ORL,
    OPHTALMOLOGIE,
    CARDIOLOGIE,
    GYNECOLOGIE,
    NEUROLOGIE,
    CHIRURGIE,
    PSYCHIATRIE,
    DENTISTE,
    ANESTHESIE,
    PHARMACIE,
    ACCOUCHEMENT,
    DERMATOLOGIE,
    PNEUMOLOGIE,
    ORTHOPEDIE,
    RADIOLOGIE,
    ANALYSE_BIO_MEDICALE
};


#endif // ENUMERATIONS_H
